### ISSUE TITLE
[Bug] Update script still looking for SteamPrefill

### ISSUE THREAD

**Issue by MrMdemiC** [tpill90/epic-lancache-prefill#10]
Hi, was trying to get this prefill working but before starting the program i started the update.sh script
I was presented with an error so i took a look into the script and found that the #unzip and below it is still looking for SteamPrefill instead off EpicPrefill:
`# Unzip`
`echo -e "${Yellow} Unzipping... ${NC}"`
`unzip -q -j -o SteamPrefill-${LATEST_TAG}-linux-x64.zip`

`# Required so executable permissions don't get overwritten by unzip`
`chmod +x SteamPrefill update.sh`

`# Cleanup`
`rm SteamPrefill-${LATEST_TAG}-linux-x64.zip`

When i change the *SteamPrefill* to *EpicPrefill* the script runs without errors :)

**Comment by Velosofy** [comment]
Feel free to make a PR :D

**Comment by Joly0** [comment]
Closed this accidentially.
@MrMdemiC Can you test and confirm its correct now?

**Comment by MrMdemiC** [comment]
> Feel free to make a PR :D

if i knew how i would love to do it hahahah :P 

> Closed this accidentially. @MrMdemiC Can you test and confirm its correct now?

i dont think it will work since the release is not updated as off this moment off writing this comment :)

when the release is updated i will test again <3

**Comment by Joly0** [comment]
> > Feel free to make a PR :D
> 
> if i knew how i would love to do it hahahah :P
> 
> > Closed this accidentially. @MrMdemiC Can you test and confirm its correct now?
> 
> i dont think it will work since the release is not updated as off this moment off writing this comment :)
> 
> when the release is updated i will test again <3

You can take the file from here
https://github.com/tpill90/epic-lancache-prefill/suites/10954170053/artifacts/554422811

**Comment by MrMdemiC** [comment]
> > > Feel free to make a PR :D
> > 
> > 
> > if i knew how i would love to do it hahahah :P
> > > Closed this accidentially. @MrMdemiC Can you test and confirm its correct now?
> > 
> > 
> > i dont think it will work since the release is not updated as off this moment off writing this comment :)
> > when the release is updated i will test again <3
> 
> You can take the file from here https://github.com/tpill90/epic-lancache-prefill/suites/10954170053/artifacts/554422811

this one kinda works 1 time but it looks at the latest release and downloads that one and overrides it...
so yes it works but only one time :)

**Comment by MrMdemiC** [comment]
BTW thanks for the help,, i am no expert in GitHub but just want to help with these small kinda things :D

**Comment by MrMdemiC** [comment]
also clicking that link downloads zip file named SteamPrefill :)

i understand that this is made quickly and still needs alot off name changing but just pointing out small things ;)

**Comment by tpill90** [comment]
Released in [v1.1.0](https://github.com/tpill90/epic-lancache-prefill/releases/tag/v1.1.0)
