### ISSUE TITLE
download does not progress

### ISSUE THREAD

**Issue by cholzer79** [tpill90/epic-lancache-prefill#13]
### **Enviroment:**

- LanCache 192.168.1.30 running on Unraid
- LanCacheDNS 192.168.1.33 running on Unraid
- LanCachePrefill running on Unraid

### **What works:**

- Steam Prefill works fine
- Battle.net Prefill works fine
- All gamelaunchers (Epic, steam, EA, battlenet, GoG) work fine on my windows machines and use the LanCache. In the image below you can see the Epic Launcher download Fortnite which goes through the LanCache at the maximum speed of my internet connection (Fornite was not in the LanCache yet)

![epic_launcher](https://user-images.githubusercontent.com/64579423/219283740-add0055d-49ee-4da5-81dc-0893e1295265.jpg)

### **What does not work:**
While I can completelly configure EpicPrefill in both the Unraid Docker as well as the standanlone windows application, the prefill download does not progress and stays at 0% with no network traffic.

The bandwitdh value shown in the Unraid Docker version is "broken" as it shows several Gbps which my internet connection is not capable of - also there is no progress and no drive activity on my LanCache nvme.

![Unraid_docker](https://user-images.githubusercontent.com/64579423/219283739-5863ad92-cd0b-4762-8f06-ea127c9277b6.jpg)

The bandwitdh indicator in the windows build is more accurate as there is no traffic.

![windows](https://user-images.githubusercontent.com/64579423/219283743-5ce909f7-cc75-44c5-b329-ae84ddcf73cc.jpg)

**LanCache Logs:**
These are the logs from an attempt to prefill City Skylines

[upstream-error.log](https://github.com/tpill90/epic-lancache-prefill/files/10753847/upstream-error.log)
[error.log](https://github.com/tpill90/epic-lancache-prefill/files/10753848/error.log)
[access.log](https://github.com/tpill90/epic-lancache-prefill/files/10753850/access.log)
[LanCache_access.log](https://github.com/tpill90/epic-lancache-prefill/files/10753851/LanCache_access.log)

### **Games tested with Unraid Prefill docker as well as the windows build:** 

- Cities Skylines - fails/no progress
- Fortnite - fails/no progress
- Doom 64 - fails/no progress
- Enter the Gungeon - fails/no progress
- Rise of the Tomb Raider: 20 Year Celebration - fails/no progress

With the Epic Launcher I can download these games, even on the same machine where the EpicPrefill.exe does not produce any download traffic.

### **Use EpicPrefill on a game that is already in the LanCache**

1. I used the Epic Launcher to download Cities Skylines through the LanCache
2. then I launched epicprefill.exe selected Cities Skylines and choose Yes to prefill

Result: EpicPrefill.exe "downloads" everything that the EpicLauncher put in the lancache.

![cachedGame](https://user-images.githubusercontent.com/64579423/219324488-f7ca7058-b556-4fe2-a16b-840595d43146.jpg)

**Comment by cholzer79** [comment]
This is a firewall/threat detection "problem".

When LanCache prefill is used it connects through "fastly-download.epicgames.com" (as seen in the LanCache prefill logs), this triggers my Firewall and Thread Protection in the UDR Pro SE.

> ET USER_AGENTS Suspicious User-Agent (USERAGENT)

When the normal EPIC Client is used to install the exact same game through the LanCache then this does not trigger the Firewall and Threat Detection which I guess is down to the client connecting to a different CDN than "fastly-download.epicgames.com"?

I have now excluded the IP of the LanCache in the Firewall & Threat Detection of my UDM Pro SE and now LanCache prefill works

**Comment by tpill90** [comment]
To add to this, it looks like the user agent defined here might be triggering the filter https://github.com/tpill90/epic-lancache-prefill/blob/master/EpicPrefill/Handlers/DownloadHandler.cs#L21

**Comment by tpill90** [comment]
Released in [v1.1.0](https://github.com/tpill90/epic-lancache-prefill/releases/tag/v1.1.0)
