### ISSUE TITLE
the "enable unicode" command causes an error

### ISSUE THREAD

**Issue by cholzer79** [tpill90/epic-lancache-prefill#14]
Win 10 pro 21H2

When I enter [the code to enable unicode](https://github.com/tpill90/epic-lancache-prefill#optional-windows-setup) I get an error.

![PS](https://user-images.githubusercontent.com/64579423/219285603-4d7fdbad-9a61-4fd6-987e-46eea1c9f05a.jpg)

`Test-Path $profile`
gives "False"

After I created a profile [following this](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.3)
`if (!(Test-Path -Path <profile-name>)) {
  New-Item -ItemType File -Path <profile-name> -Force
}`

The error using your code changed:
![PS_newError](https://user-images.githubusercontent.com/64579423/219287367-5d501553-d0a3-4169-a5bf-fe242e0fb98c.jpg)

**Comment by tpill90** [comment]
This should be fixed now.
