### ISSUE TITLE
Unreal engine showing up multiple times

### ISSUE THREAD

**Issue by mikulicf** [tpill90/epic-lancache-prefill#16]
First time running Epic prefill on the lancache server, and Unreal engine is showing multiple times for some reason.
Here's the image where it happened.
![image](https://user-images.githubusercontent.com/72322905/219981346-97d8a7c8-b229-4567-b10c-2458d53388fd.png)

**Comment by cholzer79** [comment]
I am pretty sure that is because you can download many different versions of UE - it would help to get the version displayed for each of the entries (if technically possible)

**Comment by tpill90** [comment]
How exactly do you get access to that many versions? Is it possible to do it for free so I can reproduce this?

**Comment by cholzer79** [comment]
> 
![UnrealEngine](https://user-images.githubusercontent.com/64579423/225553373-b483e453-fdab-4f88-bfae-4e1ef09a22b5.jpg)

Inside the Epic Launcher there is an "Unral Engine" section.
In there is a dropdown menu right next to "install Engine" which allows you to select the version as well as a "Engine Versions" area below.

**Comment by tpill90** [comment]
Released in [v1.1.3](https://github.com/tpill90/epic-lancache-prefill/releases/tag/v1.1.3)
