### ISSUE TITLE
Unexpected download error : A connection attempt failed because the connected party did not properly

### ISSUE THREAD

**Issue by eembling** [tpill90/epic-lancache-prefill#17]
`[10:02:12 AM] Starting A Short Hike
[10:02:34 AM] Unexpected download error : A connection attempt failed because the connected party did not properly
respond after a period of time, or established connection failed because connected host has failed to respond.
(fastly-download.epicgames.com:443)  Skipping app...`

From a PCAP (172.16.1.40 is lancache instance):
`36    3.755003    172.16.1.100    172.16.1.40    TCP    66    53437 → 443 [SYN] Seq=0 Win=62720 Len=0 MSS=8960 WS=256 SACK_PERM`

Same instance works fine using epicprefill on OSX

Trying to see why its requesting port 443 on .exe but 80 on the OSX version

From OSX
`104    10.082232    172.16.1.110    172.16.1.40    TCP    78    62416 → 80 [SYN] Seq=0 Win=65535 Len=0 MSS=1460 WS=64 TSval=2083870588 TSecr=0 SACK_PERM=1`

**Comment by tpill90** [comment]
@eembling Have you seen this issue since?  I know its been over a year now.

**Comment by eembling** [comment]
Haven't tried in a long time. If I hit it again in the future, would open a new issue

**Comment by tpill90** [comment]
Closing since its been over a year since this was opened, and I haven't received any additional info. Please feel free to reopen if it happens again.
