### ISSUE TITLE
Feature request - Total data downloaded

### ISSUE THREAD

**Issue by billthecatt** [tpill90/epic-lancache-prefill#18]
If you could, print this at the end of each run, then we could see what du -h shows and compare to see what's in the cache on disk vs just now downloaded.

Having this in all three programs would be great because then you can bash script running each of them and see what the total is. 

Thanks!

**Comment by tpill90** [comment]
Released in [v2.0.0](https://github.com/tpill90/epic-lancache-prefill/releases/tag/v2.0.0)
