### ISSUE TITLE
epic prefill missing # of apps completed

### ISSUE THREAD

**Issue by billthecatt** [tpill90/epic-lancache-prefill#19]
Other prefill apps show the following at the end of each run:

  `Prefilled 3 apps in 25.8501`

Suggest this be added to EpicPrefill so we can compare one vs the other. :) 

Thanks again for the awesome work on this solid solution!

**Comment by tpill90** [comment]
This should already be in EpicPrefill, closing since there is nothing to implement 
![image](https://github.com/tpill90/epic-lancache-prefill/assets/766513/86a8ba08-a890-4a16-9a1e-049fbdf828d1)
