### ISSUE TITLE
Login fails with 400 (Bad request)

### ISSUE THREAD

**Issue by olibertos** [tpill90/epic-lancache-prefill#25]
When attempting to initially login with an Epic Games account using the select-apps option, it produces the following output:
:~/EpicPrefill-1.1.0-linux-x64$ ./EpicPrefill select-apps
[1:28:40 PM] Please login into Epic via your browser
[1:28:40 PM] If the web page did not open automatically, please manually open the following URL: https://legendary.gl/epiclogin
Please enter the authorizationCode from the JSON response: [redacted]
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
  at HttpResponseMessage System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
  at async Task EpicPrefill.Handlers.UserAccountManager.LoginAsync()
  at async Task EpicPrefill.EpicGamesManager.InitializeAsync()
  at async ValueTask EpicPrefill.CliCommands.SelectAppsCommand.ExecuteAsync(IConsole console)

I will update when I find out if the account has any additional MFA or other limitations that may be out of the ordinary.
When using a different account, login worked successfully.

Discord name: Ed/Megabeard

**Comment by Donkeykong307** [comment]
Did you copy the whole json response or JUST the authorizationCode?

At first i copied the whole json response and i got the same error, but when i just copied the code, i got logged in.

**Comment by Chillipek** [comment]
I had same error. Tried once again logging to https://legendary.gl/epiclogin and new code worked fine

**Comment by tpill90** [comment]
I believe that there may be more than one scenario causing issues here:

- If an auth token and the refresh token have expired, then a refreshed token can't be requested.  Need to do initial login flow instead.
- If refresh token has been requested, but the new token wasn't saved for any reason (app crashed, system crashed, container crashed), then a refreshed token can't be requested.  Need to do the initial login flow as well.

**Comment by tpill90** [comment]
Fix released in [v1.2.0](https://github.com/tpill90/epic-lancache-prefill/releases/tag/v1.2.0)
