### ISSUE TITLE
Control + C doesn't pause prefill after select-apps

### ISSUE THREAD

**Issue by DecusAnima** [tpill90/epic-lancache-prefill#35]
Control + C does not pause the prefill if it started after select-apps command is ran. Reboot necessary to stop the prefill.

**Additional Details**
 - Ubuntu 22.02 Server
 - decusanima
 - US Central

**Comment by Hamsterman** [comment]
Yeah - it's the same with Steam and BattleNet prefills.

Just don't start if you are not prepared to finish it :)

**Comment by tpill90** [comment]
Released in [v2.0.0](https://github.com/tpill90/epic-lancache-prefill/releases/tag/v2.0.0)
