### ISSUE TITLE
Missing `--nocache`

### ISSUE THREAD

**Issue by Kirbo** [tpill90/epic-lancache-prefill#45]
Unlike `BattleNetPrefill` and `SteamPrefill`, `EpicPrefill` does not contain `--nocache` flag, and/or it is not working.

Consider a situation where one has a Lancache and for example deletes the cache, then runs `./EpicPrefill prefill`, the prefill will just tell user "nothing to download", which is not true, as the actual cache is empty.

..or is the EpicPrefill so wise that it can deal with a situation as mentioned above? If so, then both BattleNetPrefill and SteamPrefill would need the same kind of brains.

![image](https://github.com/tpill90/epic-lancache-prefill/assets/1077974/a8ee43a2-0b05-498b-be5e-67a08b916b49)

**Comment by Hamsterman** [comment]
The "./EpicPrefill clear-cache" works though

**Comment by tpill90** [comment]
I fixed this at some point in one of the releases.  I'm going to do a release in a little bit that I definitely know includes this, so closing this for now.
