### ISSUE TITLE
Unreal Engine still downloading multiple versions when doing `--all`

### ISSUE THREAD

**Issue by promise** [tpill90/epic-lancache-prefill#47]
**Describe the bug**
This is a follow-up to #16. I'm seeing several Unreal Engines being downloaded when doing `--all`.

**Additional Details**
 - Platform you are running EpicPrefill on: docker on linux
 - Region : EU

**Comment by tpill90** [comment]
Released in [v2.0.0](https://github.com/tpill90/epic-lancache-prefill/releases/tag/v2.0.0)
