### ISSUE TITLE
Fortnite Download From Cache Only Completes to 28%

### ISSUE THREAD

**Issue by ZurkeyDurkey** [tpill90/epic-lancache-prefill#49]
**Describe the bug**
When going through the LAN-Cache, Fortnite only completes to 28%. It doesn't matter which computer in the house I use. Epic Games launcher shows the download rate drop to 0 instantly once it reachs 28% downloaded. Filesystem was XFS on a 6TB HDD.

**Additional Details**
 - unRAID Server - Lancache, Lancache-DNS, and Lancache-Prefill in Docker
 - ZurkeyDurkey
 - Region : US West Coast

**Screenshots**
[access.log](https://github.com/tpill90/epic-lancache-prefill/files/13942850/access.log)

**Comment by tpill90** [comment]
Try the latest version [v2.0.0](https://github.com/tpill90/epic-lancache-prefill/releases/tag/v2.0.0), it should include a potential fix for this issue.

**Comment by ZurkeyDurkey** [comment]
I'll definitely try that out.   The steam cache and prefill have been disabled since shortly after my post, so I'll turn it all back on again, update Docker, and test it out.

**Comment by tpill90** [comment]
Let me know how that goes.  I'm going to go ahead and close this for now since I'm 99% sure it will fix your issue.  If it doesn't please feel free to reopen this and we'll look at it again.
