### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added. Key: AnimStarterPack

### ISSUE THREAD

**Issue by thesourcecodes** [tpill90/epic-lancache-prefill#58]
[11:24:20 PM] If the web page did not open automatically, please manually open the following URL: https://legendary.gl/epiclogin
Please enter the authorizationCode from the JSON response: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[11:30:09 PM] Retrieving owned apps
System.ArgumentException: An item with the same key has already been added. Key: AnimStarterPack

**Additional Details**
 - Platform: Unraid Latest

**Screenshots**

**Comment by thesourcecodes** [comment]
just so you know.. i resolved this problem by requesting UE marketplace to delete this ([Animation Starter pack](https://www.unrealengine.com/marketplace/en-US/product/animation-starter-pack)) asset from my UE Vault. Now its works.

**Comment by Jaffa00** [comment]
I have the same issue with a different item: ArtFashi221decb814dcV1

**Comment by tpill90** [comment]
I've reproduced this on my account sine the assets were free.  @Jaffa00 @thesourcecodes would you mind testing the build with these changes?  You can download it at the bottom from here https://github.com/tpill90/epic-lancache-prefill/actions/runs/9716900916

**Comment by Morpheus84h** [comment]
I have the Same Issue with "AncientT368aca6c4e74V2"

**Comment by tpill90** [comment]
This issue should now be resolved in the latest [v2.1.0](https://github.com/tpill90/epic-lancache-prefill/releases/tag/v2.1.0) release.  Please give it a test and let me know if the issue still persists.
