### ISSUE TITLE
[Bug] Some apps are not shown in the right order (sort by name)

### ISSUE THREAD

**Issue by Joly0** [tpill90/epic-lancache-prefill#9]
![grafik](https://user-images.githubusercontent.com/13993216/218540461-b0269cc6-0283-44f5-ad4f-02b9021d5767.png)

**Comment by Velosofy** [comment]
Confirm happening on my side aswell, perhaps uppercase > lowercase ?

**Comment by Joly0** [comment]
> Confirm happening on my side aswell, perhaps uppercase > lowercase ?

Probably yes

**Comment by tpill90** [comment]
Released in [v1.1.3](https://github.com/tpill90/epic-lancache-prefill/releases/tag/v1.1.3)
